### ISSUE TITLE
能否更改 3826号设施 的配方

### ISSUE THREAD

**Issue by Archintone** [RealSilverMoon/BoxPlusPlus#18]
由于gtnh2.7.0移除了大型分子装配室的配方，需要一组大型分子装配室作为材料的，3826号设施，无法进行制作
![图片](https://github.com/user-attachments/assets/ea1a8b65-fa99-449b-b25b-eee9ec6c2a61)

**Comment by RealSilverMoon** [comment]
OK 替换为二重压缩工作台
