### ISSUE TITLE
进不去存档

### ISSUE THREAD

**Issue by 9agj** [RealSilverMoon/BoxPlusPlus#19]
1.9版本的盒在270中只能进一次存档 如果退出存档在进就会进不去然后崩溃

**Comment by luomolhx** [comment]
@9agj 最新的代码中尝试修复了这个bug 但是还没发布release

**Comment by RealSilverMoon** [comment]
Fixed

**Comment by 9agj** [comment]
omg 我刚试了下1.91版本 还是这种本地存档只能进一次 第二次进不去*

**Comment by luomolhx** [comment]
> omg 我刚试了下1.91版本 还是这种本地存档只能进一次 第二次进不去*

试试我fork的release版本

**Comment by 9agj** [comment]
没找到

**Comment by luomolhx** [comment]
> 没找到

https://github.com/luomolhx/BoxPlusPlus/releases/tag/1.9.2-fix

**Comment by 9agj** [comment]
行这下没啥问题了 不过3826号那个配方貌似没改 要大分子

**Comment by luomolhx** [comment]
> 行这下没啥问题了 不过3826号那个配方貌似没改 要大分子

机器配方我确实没动 你是要改成什么

**Comment by luomolhx** [comment]
> 行这下没啥问题了 不过3826号那个配方貌似没改 要大分子

我看到了 等我弄一下

你在QQ群里吗  中文一群

**Comment by 9agj** [comment]
没有 我在新手群

**Comment by 9agj** [comment]
嗯 新手一群

**Comment by luomolhx** [comment]
> 嗯 新手一群

![image](https://github.com/user-attachments/assets/2ea779d1-6708-4ecc-af4c-2263ce104c5e)
艾特下我 github聊不太方便

**Comment by 9agj** [comment]
我没在中文一群喵 配方我建议改iv配方的机器就行

**Comment by 9agj** [comment]
刚发现1.93版本还是一样的 第二次进不去存档 不过3826配方倒是改好了
