### ISSUE TITLE
270中box所有配方都消失了

### ISSUE THREAD

**Issue by SafariXiu** [RealSilverMoon/BoxPlusPlus#20]
如题，所有物品的合成配方都查不到了 应该是270改了配方注册逻辑导致的

**Comment by SafariXiu** [comment]
@luomolhx

**Comment by SafariXiu** [comment]
准确来说是服务器这边，单人档没有这个问题

**Comment by luomolhx** [comment]
@SafariXiu 我这边一直玩的单人档 我用服务器看看，谢谢反馈问题
能看看你的截图吗

**Comment by luomolhx** [comment]
> 准确来说是服务器这边，单人档没有这个问题

@SafariXiu 我本地试了下 先进服务器 看不到配方 退出 打开本地存档 能看到配方 然后再进服务器就能看到配方了

**Comment by SafariXiu** [comment]
> > 准确来说是服务器这边，单人档没有这个问题
> 
> @SafariXiu 我本地试了下 先进服务器 看不到配方 退出 打开本地存档 能看到配方 然后再进服务器就能看到配方了

可能是注册时机的问题？270更新了不少东西

**Comment by luomolhx** [comment]
> > > 准确来说是服务器这边，单人档没有这个问题
> > 
> > 
> > @SafariXiu 我本地试了下 先进服务器 看不到配方 退出 打开本地存档 能看到配方 然后再进服务器就能看到配方了
> 
> 可能是注册时机的问题？270更新了不少东西

已经提交修复PR了 参考了TST的解法

**Comment by RealSilverMoon** [comment]
Fixed
