### ISSUE TITLE
打开主机GUI界面导致客户端会话被断开

### ISSUE THREAD

**Issue by InsulateJustf** [RealSilverMoon/BoxPlusPlus#6]
https://pastebin.com/Jm6VmaGn 客户端报错的log，服务端没有任何报错。
BoxPlusPlus 版本： 1.6.0
GTNH 版本： 2.5.1
Java 版本： Java 8
封装的产线： 从LV到UV的太阳能覆盖板，终极工作台的配方

另外： LV的太阳能板导入的时候只能用IC2的高级电路板而不能用纳米处理器

**Comment by RealSilverMoon** [comment]
Fixed in 2.6.1
